# Generated by Django 4.1.1 on 2022-09-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='casual_leave_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_leave_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
