# Generated by Django 4.1.1 on 2022-09-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_alter_attendance_casual_leave_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='staff_Id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
