# Generated by Django 4.1.1 on 2022-09-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_alter_attendance_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='staff_Id',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='gender',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
