# Generated by Django 4.1.1 on 2022-09-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0004_rename_date_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
